# Generated by Django 2.1.7 on 2019-02-16 10:03

from django.db import migrations, models
import django.db.models.deletion
import fp_client.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emissions', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.FloatField(verbose_name=fp_client.models.Cars)),
                ('start_lat', models.FloatField(max_length=20)),
                ('start_long', models.FloatField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('dist_traveled', models.FloatField(max_length=20)),
                ('dist_walked', models.FloatField(max_length=20)),
                ('end_time', models.DateTimeField()),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trips',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp_client.Users'),
        ),
    ]
