# Generated by Django 2.1.7 on 2019-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='start_long',
            new_name='start_lon',
        ),
        migrations.AlterField(
            model_name='trips',
            name='duration',
            field=models.FloatField(max_length=20),
        ),
    ]
