# Generated by Django 2.1.7 on 2019-02-16 19:56

from django.db import migrations, models
import fp_client.models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='start_long',
            new_name='start_lon',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='trips',
            name='car_id',
            field=models.IntegerField(verbose_name=fp_client.models.Cars),
        ),
        migrations.AlterField(
            model_name='trips',
            name='duration',
            field=models.FloatField(max_length=20),
        ),
    ]
