# Generated by Django 2.1.7 on 2019-02-16 22:53

from django.db import migrations, models
import fp_client.models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_client', '0002_auto_20190216_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='trips',
            name='end_lat',
            field=models.FloatField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='end_lon',
            field=models.FloatField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trips',
            name='car_id',
            field=models.IntegerField(verbose_name=fp_client.models.Cars),
        ),
    ]
