# Generated by Django 2.1.7 on 2019-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_client', '0002_auto_20190216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='end_lat',
            field=models.FloatField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='end_lon',
            field=models.FloatField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trips',
            name='car_id',
            field=models.IntegerField(),
        ),
    ]
