# Generated by Django 2.1.7 on 2019-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_client', '0003_auto_20190216_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='car_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
